### ISSUE TITLE
uninitialized constant Spree::Theme::CURRENT_THEME_PATH (NameError)

### ISSUE THREAD

**Issue by 99cm** [vinsol-spree-contrib/spree_themes#18]
run: rails db:migrate
brought the error
app/controllers/spree/store_controller_decorator.rb:1:in `<top (required)>': uninitialized constant Spree::Theme::CURRENT_THEME_PATH (NameError)

**Comment by PareshGupta** [comment]
Hi @99cm

After adding the gem and `bundle install`,  try 

`bundle exec rails g vinsol_spree_themes:install`.

I hope this works.

**Comment by 99cm** [comment]
I will try. Thank you very much. If the steps work, I'll close this issue.

**Comment by 99cm** [comment]
after 'bundle install', tried

'bundle exec rails g vinsol_spree_themes:install'

terminal displayed a similar error:
/spree_themes-0b8801fe8f35/app/controllers/spree/store_controller_decorator.rb:1:in `<top (required)>': uninitialized constant Spree::Theme::CURRENT_THEME_PATH (NameError)

**Comment by himanshumishra31** [comment]
Hi @99cm 

Can you please specify the spree version and ruby version you are using??

**Comment by 99cm** [comment]
We are using Ruby 2.5.0 and Spree 3.4.4.
Thank you.

**Comment by himanshumishra31** [comment]
Hi @99cm 

Can you please send the complete gemfile of your application so that we can replicate the issue and help you further.
Also please tell the steps you have done after bundle the vinsol_spree_themes gem. 

Thank you

**Comment by 99cm** [comment]
@himanshumishra31 
After bundle, could not complete rake db migrate, nor run 'rails g vinsol_spree_themes:install' because of uninitialized constant error.
`source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem 'rails', '5.1.5'
gem 'pg', '>= 0.18', '< 2.0'
gem 'bootstrap-sass', '~> 3.3.7'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'turbolinks', '~> 5'

gem 'coffee-rails', '~> 4.2.0'
gem 'coffee-script-source', '1.12.2'

gem 'jbuilder', '~> 2.5'
gem 'jquery-rails'

gem 'spree', '~> 3.4.4'
gem 'spree_auth_devise', '~> 3.3'
gem 'devise', '~> 4.4'
gem 'spree_gateway', '~> 3.3'

gem 'invisible_captcha', github: '99cm/invisible_captcha', branch: 'master'
gem 'spree_active_shipping', github: 'spree-contrib/spree_active_shipping'
gem 'spree_address_book', github: 'spree-contrib/spree_address_book'
gem 'spree_mail_settings', github: 'spree-contrib/spree_mail_settings'
gem 'spree_contact_us', github: '99cm/spree_contact_us', branch: 'master'

#gem 'spree_email_to_friend', github: '99cm/spree_email_to_friend', branch: 'master'
gem 'spree_html_invoice' , github: '99cm/spree-html-invoice', branch: 'master'
gem "spree_comments", github: 'spree-contrib/spree_comments'
gem 'spree_recently_viewed', github: 'spree-contrib/spree_recently_viewed'
gem 'spree_reviews', github: 'spree-contrib/spree_reviews'
#gem 'spree_loyalty_points', github: '99cm/spree_loyalty_points', branch: 'master'
gem 'spree_product_assembly', github: 'spree-contrib/spree-product-assembly'
gem 'spree_reffiliate', github: '99cm/spree_reffiliate', branch: 'master'
gem 'spree_related_products', github: 'spree-contrib/spree_related_products'

gem 'spree_simple_sales', github: '99cm/spree_simple_sales', branch: 'master'
gem 'spree_sitemap', github: 'spree-contrib/spree_sitemap'
gem 'spree_slider', github: 'spree-contrib/spree_slider'
gem 'spree_social', github: 'spree-contrib/spree_social'
gem 'spree_volume_pricing', github: 'spree-contrib/spree_volume_pricing'
gem 'spree_wishlist', github: 'spree-contrib/spree_wishlist'
#gem 'sqlite3'

gem 'spree_editor', github: 'spree-contrib/spree_editor'
gem 'globalize', github: 'globalize/globalize'
gem 'spree_i18n', github: 'spree-contrib/spree_i18n'
gem 'spree_globalize', github: 'spree-contrib/spree_globalize', branch: 'master'
gem 'spree_static_content', github: 'spree-contrib/spree_static_content'
gem 'spree_blogging_spree', github: '99cm/spree-blogging-spree', branch: 'master'
gem 'kaminari-core'

gem 'whenever', :require => false
gem 'elasticsearch', '~> 6.0', '>= 6.0.2'
gem 'elasticsearch-model', github: 'elastic/elasticsearch-rails'
#gem 'elasticsearch-persistence', github: 'elastic/elasticsearch-rails'
#gem 'elasticsearch-rails', github: 'elastic/elasticsearch-rails'
#gem 'spree_elasticsearch', github: '99cm/spree_elasticsearch'
gem 'searchkick'
gem 'spree_searchkick', github: 'ronzalo/spree_searchkick', branch: 'master'
gem 'analytics-ruby'
gem 'spree_analytics_trackers', github: 'spree-contrib/spree_analytics_trackers'
#gem 'spree_events_tracker', github: 'vinsol-spree-contrib/spree_events_tracker', branch: 'master'
#gem 'spree_admin_insights'
#gem 'vinsol_spree_themes', github: 'vinsol-spree-contrib/spree_themes', branch: 'master'
#gem 'sprockets-helpers', '~> 1.2.1'

group :development, :test do
  gem 'byebug'
  gem 'capistrano', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-figaro', require: false
  gem 'capistrano-rails', require: false
  gem 'capistrano-rvm', require: false
  gem 'capistrano3-puma', require: false
  gem 'web-console', '~> 2.0'
end`

Those commented out gems are not able to complete installation.

**Comment by himanshumishra31** [comment]
Hi @99cm 

I used your gemfile and it's working fine for me so i couldn't replicate the issue.
Please create a new spree app and then try to install the extension. I hope that would work.

Thank you
